name:                biz-lang
version:             0.1.0.0
license:             MIT
author:              "Erhan Dragoș [aut], Ion Tulei [aut]"
maintainer:          "Ion Tulei <tuleiion2014@gmail.com>"
copyright:           "2024 Erhan Dragoș, Ion Tulei"

extra-source-files:
- README.md

description:         Implementation of BizLang.

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && < 3.2
- sprockell >= 2022.0
- hspec >= 2.8 && < 2.9
- QuickCheck >= 2.14 && < 2.15
- containers
- directory

library:
  source-dirs: src

executables:
  biz-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - biz-lang

tests:
  biz-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - biz-lang
